secret: ${SECRET}

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

#server:
#  tomcat:
#    accesslog:
#      enabled: true
#      basedir: .
#      directory: logs
#      suffix: .log
#      prefix: access_log
#      file-date-format: '.yyyy-MM-dd'
#      # pattern: common
#      pattern: '%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b'

